// <auto-generated />
using System;
using EstatePlanner.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EstatePlanner.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260717203419_AddTrustAndVault")]
    partial class AddTrustAndVault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EstatePlanner.Api.Models.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BeneficiaryName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BeneficiaryStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("HeldInTrust")
                        .HasColumnType("boolean");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("OwnerPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.EstateDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BackupAgentPersonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EffectiveImmediately")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("ExecutedOn")
                        .HasColumnType("date");

                    b.Property<string>("ExecutionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeHipaa")
                        .HasColumnType("boolean");

                    b.Property<string>("LifeSupport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("OrganDonation")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PrincipalPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId", "Type")
                        .IsUnique();

                    b.ToTable("EstateDocuments");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.Household", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.TrustPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BackupTrusteePersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("DistributionStrategy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateOnly?>("ExecutedOn")
                        .HasColumnType("date");

                    b.Property<string>("ExecutionNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("GrantorPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SuccessorTrusteePersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique();

                    b.ToTable("TrustPlans");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.VaultItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("VaultItems");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.WillPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BackupExecutorPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BackupGuardianPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExecutedOn")
                        .HasColumnType("date");

                    b.Property<Guid?>("ExecutorPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GuardianPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResiduaryStrategy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StorageLocation")
                        .HasColumnType("text");

                    b.Property<Guid?>("TestatorPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WaiveExecutorBond")
                        .HasColumnType("boolean");

                    b.Property<string>("Witness1Name")
                        .HasColumnType("text");

                    b.Property<string>("Witness2Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId")
                        .IsUnique();

                    b.ToTable("WillPlans");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.Asset", b =>
                {
                    b.HasOne("EstatePlanner.Api.Models.Household", "Household")
                        .WithMany("Assets")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.EstateDocument", b =>
                {
                    b.HasOne("EstatePlanner.Api.Models.Household", "Household")
                        .WithMany("Documents")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.Person", b =>
                {
                    b.HasOne("EstatePlanner.Api.Models.Household", "Household")
                        .WithMany("People")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.TrustPlan", b =>
                {
                    b.HasOne("EstatePlanner.Api.Models.Household", "Household")
                        .WithOne("TrustPlan")
                        .HasForeignKey("EstatePlanner.Api.Models.TrustPlan", "HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("EstatePlanner.Api.Models.ResiduaryShare", "DistributionShares", b1 =>
                        {
                            b1.Property<Guid>("TrustPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name");

                            b1.Property<int>("Percent");

                            b1.Property<Guid?>("PersonId");

                            b1.HasKey("TrustPlanId", "__synthesizedOrdinal");

                            b1.ToTable("TrustPlans");

                            b1
                                .ToJson("DistributionShares")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("TrustPlanId");
                        });

                    b.Navigation("DistributionShares");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.VaultItem", b =>
                {
                    b.HasOne("EstatePlanner.Api.Models.Household", "Household")
                        .WithMany("VaultItems")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.WillPlan", b =>
                {
                    b.HasOne("EstatePlanner.Api.Models.Household", "Household")
                        .WithOne("WillPlan")
                        .HasForeignKey("EstatePlanner.Api.Models.WillPlan", "HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("EstatePlanner.Api.Models.WillGift", "Gifts", b1 =>
                        {
                            b1.Property<Guid>("WillPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Description")
                                .IsRequired();

                            b1.Property<string>("RecipientName");

                            b1.Property<Guid?>("RecipientPersonId");

                            b1.HasKey("WillPlanId", "__synthesizedOrdinal");

                            b1.ToTable("WillPlans");

                            b1
                                .ToJson("Gifts")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WillPlanId");
                        });

                    b.OwnsMany("EstatePlanner.Api.Models.ResiduaryShare", "ResiduaryShares", b1 =>
                        {
                            b1.Property<Guid>("WillPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name");

                            b1.Property<int>("Percent");

                            b1.Property<Guid?>("PersonId");

                            b1.HasKey("WillPlanId", "__synthesizedOrdinal");

                            b1.ToTable("WillPlans");

                            b1
                                .ToJson("ResiduaryShares")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("WillPlanId");
                        });

                    b.Navigation("Gifts");

                    b.Navigation("Household");

                    b.Navigation("ResiduaryShares");
                });

            modelBuilder.Entity("EstatePlanner.Api.Models.Household", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Documents");

                    b.Navigation("People");

                    b.Navigation("TrustPlan");

                    b.Navigation("VaultItems");

                    b.Navigation("WillPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
